services:
  web:
    platform: linux/amd64
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec unicorn -c config/unicorn.rb -E production"
    volumes:
      - .:/chronos-smart2
    ports:
      - "4000:4000"