version: '3'
services:
  web:
    platform: linux/amd64
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/chronos-smart2
    ports:
      - "4000:4000"
    develop:
      watch:
        - action: rebuild
          path: .
