services:
  web:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -fR shared/pids/* ; bundle exec unicorn -E production -c config/unicorn.rb"
    volumes:
      - .:/chronos-smart2      
      - /chronos-smart2/shared/log
      - /chronos-smart2/shared/pids
      - /chronos-smart2/shared/sockets
    ports:
      - "4000:4000"
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "4000:4000"
    volumes_from:
      - web
    links:
      - web:web