version: '3'
services:

  smart-web:
    platform: linux/amd64
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:create && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/chronos-smart2
    environment:
      - PGHOST=${PG_HOST}
      - PGUSER=${PG_USER}
    ports:
      - "3000:3000"
    depends_on:
      - smart-db
    links:
      - smart-db

  smart-db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - .pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
