class Menu < ActiveRecord::Base

	def self.docs_autorizacao(params)
		sql = "SELECT FF.DATA,
									FF.ID,
									FF.MOEDA,
									FF.PERSONA_NOME,
									FF.SIGLA_PROC, 
							       FF.COD_PROC, 
							       FF.DOC, 
							       (SELECT SUM(VP.TOTAL_GUARANI) FROM VENDAS_PRODUTOS VP WHERE VP.VENDA_ID = FF.COD_PROC) AS TOTAL_GS,
							       (SELECT SUM(VP.TOTAL_DOLAR) FROM VENDAS_PRODUTOS VP WHERE VP.VENDA_ID = FF.COD_PROC) AS TOTAL_US,
							       FF.AUTORIZACAO
							FROM FORM_FISCALS FF WHERE FF.STATUS = 1 AND FF.SIGLA_PROC = 'VT' AND FF.AUTORIZACAO = FALSE

							UNION ALL

							SELECT FF.DATA,
									FF.ID,
									FF.MOEDA,
									FF.PERSONA_NOME,	
									FF.SIGLA_PROC, 
							       FF.COD_PROC, 
							       FF.DOC, 
									(SELECT SUM( (CD.COBRO_GUARANI + CD.INTERES_GUARANI) - CD.DESCONTO_GUARANI) FROM COBROS_DETALHES CD WHERE CD.COBRO_ID = FF.COD_PROC) AS TOTAL_GS,
									(SELECT SUM( (CD.COBRO_DOLAR + CD.INTERES_DOLAR) - CD.DESCONTO_DOLAR) FROM COBROS_DETALHES CD WHERE CD.COBRO_ID = FF.COD_PROC) AS TOTAL_US,
							       FF.AUTORIZACAO
							FROM FORM_FISCALS FF WHERE FF.STATUS = 1 AND FF.SIGLA_PROC = 'CB' AND FF.AUTORIZACAO = FALSE

							UNION ALL

							SELECT FF.DATA,
									FF.ID,
									FF.MOEDA,
									FF.PERSONA_NOME,	
									FF.SIGLA_PROC, 
							       FF.COD_PROC, 
							       FF.DOC, 
							       (SELECT SUM(VP.VALOR_GUARANI) FROM NOTA_CREDITOS_DOCS VP WHERE VP.NOTA_CREDITO_ID = FF.COD_PROC) AS TOTAL_GS,
							       (SELECT SUM(VP.VALOR_DOLAR) FROM NOTA_CREDITOS_DOCS VP WHERE VP.NOTA_CREDITO_ID = FF.COD_PROC) AS TOTAL_US,
							       FF.AUTORIZACAO
							FROM FORM_FISCALS FF WHERE FF.STATUS = 1 AND FF.SIGLA_PROC = 'CBP' AND FF.AUTORIZACAO = FALSE
							ORDER BY 1
							limit 20

							"
		FormFiscal.find_by_sql(sql)
	end
end
